name: Build SLES Binary (GLIBC 2.31 Compatible)

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    name: Build on SLES 15 SP3 (GLIBC 2.31)
    runs-on: ubuntu-latest
    container:
      # Using the public SLES 15 SP3 base image for GLIBC 2.31 compatibility
      image: registry.suse.com/suse/sle15:15.3
      
    steps:
      - name: Install Essential Build Tools and Dependencies 📦
        # Install 'tar', 'gcc'/'make', and the OpenLDAP development library.
        # SWITCHED to the short flag '-G' to skip GPG checks.
        run: |
          # Install essential tools: tar, gcc, make
          zypper install -y -G tar gcc make
          
          # Install OpenLDAP development libraries.
          # Try the most common SLES name first, with a fallback.
          zypper install -y -G libldap-devel || zypper install -y -G libldap-2_4-2-devel
          
---
      - name: Checkout Source Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Trust workspace for git
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

---
      - name: Set up Go 1.22 🚀
        # Reliably installs Go, bypassing issues with the image's package repo.
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          cache: true
          cache-key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}

---
      - name: Build linux amd64 binary (CGO Enabled) 🔨
        # CGO_ENABLED=1 links dynamically against the SLES 15 SP3 glibc 2.31 libraries.
        run: |
          mkdir -p dist
          # The Go compiler is in the PATH.
          GOOS=linux GOARCH=amd64 CGO_ENABLED=1 go build -o dist/openldap_exporter ./cmd/openldap_exporter

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: openldap-exporter-linux-amd64
          path: dist/openldap_exporter
