name: Build SLES Binary (GLIBC 2.31 Compatible)

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    name: Build on SLES 15 SP3 (GLIBC 2.31)
    runs-on: ubuntu-latest
    container:
      # Using the public SLES 15 SP3 base image for GLIBC 2.31 compatibility
      image: registry.suse.com/suse/sle15:15.3
      
    steps:
      - name: Install Essential Build Tools and Dependencies 📦
        # Use the explicit flag --no-check-signature to bypass the expired GPG key.
        run: |
          # 1. Force a refresh of repositories to update metadata
          zypper ref -f
          
          # 2. Install essential tools (tar, gcc, make)
          # We use the explicit flag --no-check-signature
          zypper install -y --no-check-signature tar gcc make
          
          # 3. Install OpenLDAP development libraries.
          # Try the most common SLES name first, with a fallback.
          zypper install -y --no-check-signature libldap-devel || zypper install -y --no-check-signature libldap-2_4-2-devel
          
---
      - name: Checkout Source Code
        # This will now succeed because 'tar' is installed in the previous step.
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Trust workspace for git
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

---
      - name: Set up Go 1.22 🚀
        # Reliably installs Go, bypassing issues with the image's package repo.
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          cache: true
          cache-key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}

---
      - name: Build linux amd64 binary (CGO Enabled) 🔨
        # CGO_ENABLED=1 links dynamically against the SLES 15 SP3 glibc 2.31 libraries.
        run: |
          mkdir -p dist
          # The Go compiler is in the PATH.
          GOOS=linux GOARCH=amd64 CGO_ENABLED=1 go build -o dist/openldap_exporter ./cmd/openldap_exporter

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: openldap-exporter-linux-amd64
          path: dist/openldap_exporter
